version: '3'

networks:
  docker-go:

services:
  server:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go
      - database
    networks:
      - docker-go
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "9000:9000"
    networks:
      - docker-go
  database:
    image: mongo
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: nelwhix
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - docker-go

